### ISSUE TITLE
init navigation between screens

### ISSUE THREAD

**Issue by BillyLuisNeedham** [BillyLuisNeedham/WhatsInTheFridgeCompose#5]
# Points
- Just use simple holder screens
- Navigator component that is passed to each activity or fragment and manages all of the navigation routes
  - Use an interface that is then implemented (better for testing)

## Todo 
- [x] Work out every navigation route required
- [x] Create holder screens for each screen
- [x] Wire in navigation from screen to screen

**Comment by BillyLuisNeedham** [comment]
# Work out every navigation route required
## Screens
- Food list
- Add food
- Sort by bottom dialog

## Nav routes
- Food list to sort by
- Food list to add food

**Comment by BillyLuisNeedham** [comment]
# Create holder screens for each screen
- [x] Add food screen
- [x] Food list screen
- [x] Sort by bottom dialog

In compose bottom dialog will be handled by add food screen
